/**
 ******************************************************************************
 * @file           : lib.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Library body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "uart2.h"
#include "stm32f4xx.h"
#include <stdint.h>

unsigned long f_cpu;

/** Functions ----------------------------------------------------------------*/
void uart2_set_fcpu(unsigned long freq)
{
	f_cpu = freq;
}

uart_err_type_t uart2_config(uint32_t baud, uart_data_type_t ndata, uart_stop_type_t nstop)
{

	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;	// enable UART2 clock
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;	// enable GPIOA clock

	// alternate function mode on TX (PA2) and RX (PA3)
	GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;
	GPIOA->MODER &= ~(GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0);

	// select alternate function mode 7 for each
	GPIOA->AFR[0] &= ~(GPIO_AFRL_AFRL2 | GPIO_AFRL_AFRL3);
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_0 | GPIO_AFRL_AFRL3_0 |
					GPIO_AFRL_AFRL2_1 | GPIO_AFRL_AFRL3_1 |
					GPIO_AFRL_AFRL2_2 | GPIO_AFRL_AFRL3_2;

	USART2->CR1 |= USART_CR1_UE;			// UART2 enable

	if (ndata == USART_DATA_8)
	{
		USART2->CR1 &= ~USART_CR1_M;		// 1 start, 8 data, n stop
	}
	else if (ndata == USART_DATA_9)
	{
		USART2->CR1 |= USART_CR1_M;			// 1 start, 9 data, n stop
	}
	else
	{
		return USART_INVALID_NDATA;
	}

	if (nstop == USART_STOP_1)
	{
		USART2->CR2 &= ~USART_CR2_STOP;		// 1 stop bit
	}
	else if (nstop == USART_STOP_HALF)
	{
		USART2->CR2 &= ~USART_CR2_STOP;		// half stop bit
		USART2->CR2 |= USART_CR2_STOP_0;
	}
	else if (nstop == USART_STOP_2)
	{
		USART2->CR2 &= ~USART_CR2_STOP;		// 2 stop bits
		USART2->CR2 |= USART_CR2_STOP_1;
	}
	else
	{
		return USART_INVALID_NSTOP;
	}

	// pg. 519 STM32F401RE reference
	float usart_div = f_cpu / (2 * 16.0 * baud);		// APB1 bus is 1/2 clock speed of f_cpu
	uint16_t mantissa = (uint16_t) usart_div;
	uint8_t fraction = (uint8_t) ((usart_div - mantissa) * 16);
	USART2->BRR = mantissa << 4 | fraction;

	USART2->CR1 |= USART_CR1_TE;		// transmitter enable
	USART2->CR1 |= USART_CR1_RE;		// receiver enable

	return USART_OK;
}

uart_err_type_t uart2_dma1_config(uint32_t baud, uart_data_type_t ndata, uart_stop_type_t nstop)
{
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;	// enable UART2 clock
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;	// enable GPIOA clock
	RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN;		// enable DMA1 clock

	/* Setup DMA1 for transmission */
	// disable DMA1 to configure
	DMA1_Stream6->CR &= ~DMA_SxCR_EN;
	while (DMA1_Stream6->CR & DMA_SxCR_EN);

	// select stream 6, channel 4 for USART2_TX
	DMA1_Stream6->CR &= ~DMA_SxCR_CHSEL;
	DMA1_Stream6->CR |= DMA_SxCR_CHSEL_2;

	// disable direct mode
	DMA1_Stream6->FCR |= DMA_SxFCR_DMDIS;

	// normal mode, low priority, 1 byte data size (memory and peripheral)
	DMA1_Stream6->CR &= ~(DMA_SxCR_DBM | DMA_SxCR_PL | DMA_SxCR_MSIZE | DMA_SxCR_PSIZE);

	// memory increment mode
	DMA1_Stream6->CR |= DMA_SxCR_MINC;

	// fixed peripheral pointer
	DMA1_Stream6->CR &= ~DMA_SxCR_PINC;

	// disable circular mode
	DMA1_Stream6->CR &= ~DMA_SxCR_CIRC;

	// memory to peripheral mode
	DMA1_Stream6->CR &= ~DMA_SxCR_DIR_1;
	DMA1_Stream6->CR |= DMA_SxCR_DIR_0;

	// peripheral address is USART2_DR
	DMA1_Stream6->PAR = (uint32_t)&(USART2->DR);

	/* Setup UART2 for transmission using DMA1 */
	// alternate function mode on TX (PA2) and RX (PA3)
	GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;
	GPIOA->MODER &= ~(GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0);

	// select alternate function mode 7 for each
	GPIOA->AFR[0] &= ~(GPIO_AFRL_AFRL2 | GPIO_AFRL_AFRL3);
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_0 | GPIO_AFRL_AFRL3_0 |
					GPIO_AFRL_AFRL2_1 | GPIO_AFRL_AFRL3_1 |
					GPIO_AFRL_AFRL2_2 | GPIO_AFRL_AFRL3_2;

	USART2->CR1 |= USART_CR1_UE;			// UART2 enable

	if (ndata == USART_DATA_8)
	{
		USART2->CR1 &= ~USART_CR1_M;		// 1 start, 8 data, n stop
	}
	else if (ndata == USART_DATA_9)
	{
		USART2->CR1 |= USART_CR1_M;			// 1 start, 9 data, n stop
	}
	else
	{
		return USART_INVALID_NDATA;
	}

	if (nstop == USART_STOP_1)
	{
		USART2->CR2 &= ~USART_CR2_STOP;		// 1 stop bit
	}
	else if (nstop == USART_STOP_HALF)
	{
		USART2->CR2 &= ~USART_CR2_STOP;		// half stop bit
		USART2->CR2 |= USART_CR2_STOP_0;
	}
	else if (nstop == USART_STOP_2)
	{
		USART2->CR2 &= ~USART_CR2_STOP;		// 2 stop bits
		USART2->CR2 |= USART_CR2_STOP_1;
	}
	else
	{
		return USART_INVALID_NSTOP;
	}

	// pg. 519 STM32F401RE reference
	float usart_div = f_cpu / (2 * 16.0 * baud);		// APB1 bus is 1/2 clock speed of f_cpu
	uint16_t mantissa = (uint16_t) usart_div;
	uint8_t fraction = (uint8_t) ((usart_div - mantissa) * 16);
	USART2->BRR = mantissa << 4 | fraction;

	USART2->CR3 |= USART_CR3_DMAT;		// enable DMA transmitter

	USART2->CR1 |= USART_CR1_TE;		// transmitter enable
	USART2->CR1 |= USART_CR1_RE;		// receiver enable

	return USART_OK;
}

uart_err_type_t uart2_write_byte(uint8_t data)
{
	while (!((USART2->SR) & USART_SR_TXE));		// wait for TX buffer empty
	USART2->DR = data;

	return USART_OK;
}


uart_err_type_t uart2_write(uint8_t * data, uint8_t len)
{
	for (uint8_t i = 0; i < len; i++)
	{
		uart2_write_byte(data[i]);
	}

	return USART_OK;
}

void uart2_dma1_write(uint16_t n, uint8_t * data)
{
	while (!(USART2->SR & USART_SR_TXE));	// wait for transmit data register empty
	USART2->SR &= ~USART_SR_TC;				// clear flag

	DMA1_Stream6->CR &= ~DMA_SxCR_EN;		// disable DMA stream
	while (DMA1_Stream6->CR & DMA_SxCR_EN);

	// clear flags
	DMA1->HIFCR |= DMA_HIFCR_CTCIF6 | DMA_HIFCR_CHTIF6 | DMA_HIFCR_CTEIF6 | DMA_HIFCR_CDMEIF6 | DMA_HIFCR_CFEIF6;

	DMA1_Stream6->NDTR = n;					// set # of data items to transfer
	DMA1_Stream6->M0AR = (uint32_t) data;	// pointer to data
	DMA1_Stream6->CR |= DMA_SxCR_EN;		// enable DMA stream
}
