M48
; DRILL file KiCad 10.0.0 date 2026-09-07T00:58:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T00:58:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X138.045Y-93.5
X138.045Y-96.5
X159.2Y-117.55
X163.6Y-117.55
T2
X146.615Y-117.2
X152.965Y-117.2
M30
